apps/books/urls.py
from django.urls import path

from apps.books.views import BookListView, BookDetailView, AddReviewView, AddBookView

app_name = "books"

urlpatterns = [
    path('', BookListView.as_view(), name="book-list"),
    path('add_book/', AddBookView.as_view(), name="add-book"),
    path('<slug:slug>/', BookDetailView.as_view(), name="book-detail"),
    path('<int:pk>', AddReviewView.as_view(), name="add-review")

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home"),
    path('user/', include("apps.users.urls")),
    path('books/', include("apps.books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/books/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import CharField, TextField, SlugField, TextChoices, IntegerField, ImageField, URLField, \
    ManyToManyField, ForeignKey, CASCADE, DateField, EmailField
from apps.shared.models import AbstractModel


class LanguageChoice(TextChoices):
    ENGLISH = "en", "English"
    FRANCE = "fr", "France"
    RUSSIAN = "ru", "Russian"
    ARABIC = "ab", "Arabic"
    UZBEK = "uz", "Uzbek"


class Book(AbstractModel):
    title = CharField(max_length=128)
    slug = SlugField(unique=True)
    description = TextField()
    published = DateField(default=True)
    isbn = CharField(max_length=128, unique=True)
    language = CharField(max_length=7, choices=LanguageChoice.choices, default=LanguageChoice.ENGLISH)
    page = IntegerField()
    cover = ImageField(upload_to="books/cover/%Y/%m/%d", default="book_cover.jpg")
    genre = ManyToManyField("books.BookGenre", "books")
    authors = ManyToManyField("books.BookAuthor", "books")


class BookAuthor(AbstractModel):
    first_name = CharField(max_length=56)
    last_name = CharField(max_length=56)
    birthdate = DateField()
    website = URLField()
    avatar = ImageField(upload_to="authors/avatar/%Y/%m/%d")
    about = TextField()
    email = EmailField(unique=True)


class BookGenre(AbstractModel):
    name = CharField(max_length=128)


class BookReview(AbstractModel):
    book = ForeignKey("books.Book", CASCADE, "reviews")
    user = ForeignKey("users.User", CASCADE, "reviews")
    body = TextField()
    rating = IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    like_count = IntegerField(default=0)

apps/books/forms.py
from django.db.models.functions import datetime
from django.forms import ModelForm, IntegerField, Widget, Textarea
from apps.books.models import BookReview, Book, BookAuthor, BookGenre
from django import forms


# class Textarea(Widget):
#     template_name = "django/forms/widgets/textarea.html"
#
#     def __init__(self, attrs=None):
#         # Use slightly better defaults than HTML's 20x2 box
#         default_attrs = {"cols": "10", "rows": "3"}
#         if attrs:
#             default_attrs.update(attrs)
#         super().__init__(default_attrs)


class AddBookReviewForm(ModelForm):
    rating = IntegerField(min_value=1, max_value=5)
    body = Textarea(attrs={"rows": "3"})

    class Meta:
        model = BookReview
        fields = ("body", "rating")


class CustomMMCF(forms.ModelMultipleChoiceField):
    def label_from_instance(self, member):
        return "%s" % member.first_name


class CustomMMCF1(forms.ModelMultipleChoiceField):
    def label_from_instance(self, member):
        return "%s" % member.name


class AddBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description', 'description', 'isbn', 'language', 'page', 'cover', 'genre',
                  'authors']

    genre = CustomMMCF1(
        queryset=BookGenre.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    authors = CustomMMCF(
        queryset=BookAuthor.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

apps/books/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from apps.books.forms import AddBookReviewForm, AddBookForm
from apps.books.models import Book, BookReview
from apps.users import User


class BookListView(View):
    def get(self, request):
        queryset = Book.objects.all()
        param = request.GET.get("q", None)

        if param is not None:
            queryset = queryset.filter(title__icontains=param)
        context = {
            "books": queryset,
            "param": param
        }
        return render(request, "books/book-list.html", context=context)


class BookDetailView(View):
    def get(self, request, slug):
        book = Book.objects.get(slug=slug)
        form = AddBookReviewForm()
        context = {
            "book": book,
            "form": form
        }
        return render(request, "books/book-detail.html", context=context)


class AddReviewView(View):
    def post(self, request, pk):
        book = Book.objects.get(id=pk)
        user = User.objects.get(username=request.user.username)
        form = AddBookReviewForm(request.POST)
        if form.is_valid():
            BookReview.objects.create(
                user=user,
                book=book,
                body=form.cleaned_data.get("body"),
                rating=form.cleaned_data.get("rating")
            )
            return redirect(reverse("books:book-detail", kwargs={"slug": book.slug}))
        else:
            context = {
                "book": book,
                "form": form
            }
            return render(request, "books/book-detail.html", context=context)


class AddBookView(View):
    def post(self, request):
        form = AddBookForm(data=request.POST)
        if form.is_valid():
            queryset = Book.objects.all()
            param = request.GET.get("q", None)

            if param is not None:
                queryset = queryset.filter(title__icontains=param)
            context = {
                "books": queryset,
                "param": param
            }
            form.save()
            messages.success(request, "Book successfully added!")
            return redirect(reverse('books:book-list', kwargs={context}))

        else:
            return render(request, "books/add_book.html", context={'form': form})

    def get(self, request):
        form = AddBookForm(data=request.GET)
        return render(request, "books/add_book.html", {'form': form})

templates/books/book-detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Book Detail{% endblock %}
{% block content %}
    <h3>Book Detail Page</h3>
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ book.cover.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ book.title }}</h5>
            <span class="my-2">Authors:
                {% for author in book.authors.all %}
                    <a href="" class="fw-bold">
                    {{ author.first_name }} {{ author.last_name }}
                    </a>
                {% endfor %}
            </span><br>
            <span>Published: {{ book.published }}</span> <br>
            <span>Genres:
                {% for genr in book.genre.all %}
                    <a href="" class="fw-light">{{ genr.name }}</a>
                {% endfor %}

            </span>

            <p>{{ book.description }}</p>
            <p>ISBN: {{ book.isbn }}</p>
            <p>Page: {{ book.page }}</p>
        </div>


    </div>
    <hr>
    <div class="row">
        <div class="col-4">
            <form action="{% url 'books:add-review' book.pk %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="mt-1 btn btn-success">Add Review</button>
            </form>
        </div>
    </div>
    {% if book.reviews %}
        <div class="row">
            <h3>Reviews</h3>
            <div class="col-9">
                {% for review in book.reviews.all %}
                    <div class="card my-2">
                        <div class="card-header">
                            {{ review.user.username }} rated {{ review.rating }}

                        </div>
                        <div class="card-body">
                            <h5 class="card-title">       {{ review.user.username }}</h5>
                            <p class="card-text">{{ review.body }}</p>
                            <a href="#" class="btn btn-light">Like 👍</a> <span
                                class="fw-lighter">{{ review.like_count }} likes </span>
                        </div>
                    </div>
                {% endfor %}

            </div>

        </div>
    {% else %}
        <h3>No Reviews</h3>
    {% endif %}

{% endblock %}

templates/books/book-list.html
{% extends "base.html" %}

{% block title %} Books {% endblock %}
{% block content %}


    <div class="py-4">
        <h3>Books         </h3>
        <button><a href ='{% url 'books:add-book' %}'>Create Book</a></button>
    </div>
    {% for book in books %}
        <div class="row mb-3">
            <div class="col-2">
                <img src="{{ book.cover.url }}" alt="No Pic" class="img-fluid">
            </div>
            <div class="col-6">
                <a href="{% url 'books:book-detail' book.slug %}"> {{ book.title }}</a>
                <p>{{ book.description }}</p>
            </div>
        </div>
    {% empty %}
        <h3>No Books</h3>
    {% endfor %}

{% endblock %}