apps/books/urls.py
from django.urls import path

from apps.books.views import BookListView, BookDetailView, AddReviewView, AddBookView

app_name = "books"

urlpatterns = [
    path('', BookListView.as_view(), name="book-list"),
    path('add_book/', AddBookView.as_view(), name="add-book"),
    path('<slug:slug>/', BookDetailView.as_view(), name="book-detail"),
    path('<int:pk>', AddReviewView.as_view(), name="add-review")

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home"),
    path('user/', include("apps.users.urls")),
    path('books/', include("apps.books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Bootstrap demo
        {% endblock %}
    </title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary mt-1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Goodreads Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'books:book-list' %}">Books</a>
                    </li>
                    <li>
                        <form action="{% url 'books:book-list' %}" method="get" class="d-flex ms-4">
                            {% csrf_token %}
                            <input type="text" class="form-control" name="q" value="{{ param }}"
                                   placeholder="Search book">
                            <button type="submit" class="btn btn-secondary">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
            <div class="me-5 mt-2">
                <ul type="none" class="me-5">

                    {% if request.user.is_authenticated %}
                        <button class="btn btn-secondary">{{ request.user.username }}</button>
                    {% else %}
                         <button class="btn btn-primary"> Login</button>
                        <button class="btn btn-primary"> Register</button>
                    {% endif %}



                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="mt-2 alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</div>
<script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}

        <h3>Home Page</h3>
        <p>Goodreads is an American social cataloging website and a subsidiary of Amazon[1]
            that allows individuals to search its database of books, annotations, quotes, and
            reviews. Users can sign up and register books to generate library catalogs and
            reading lists. They can also create their own groups of book suggestions, surveys,
            polls, blogs, and discussions. The website's offices are located in San Francisco.[2]
            Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler
            and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5]
            and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million
            members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013,
            Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads
            announced their user base had grown to 20 million members.[9]

</p>
{% endblock %}